### used for deployment on the raspberypi 4 
version: "3"

  mongodocker:
    container_name: "MongoDBPi"
    image: mongo:bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sandro
      - MONGO_INITDB_ROOT_PASSWORD=12345asdF
    volumes:
      - ~/MongoDB/mongoApp/data:/data/db
