### For Deployment in production environments - gets committed into the repo
version: "3"

services:
  expressdocker:
    container_name: "NodeServerProd"
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}
      - VIRTUAL_HOST=dockerapp.axfert.com
      - LETSENCRYPT_HOST=dockerapp.axfert.com
    command: npm run prod

  webdefault:
    container_name: "nginxProd"
    image: nginx
    environment:
      - VIRTUAL_HOST=axfert.com
      - LETSENCRYPT_HOST=axfert.com
    restart: always

  webexpressapp:
    container_name: "nginxAppProd"
    image: nginx
    environment:
      - VIRTUAL_HOST=app.axfert.com
      - LETSENCRYPT_HOST=app.axfert.com
    volumes:
      - ~/Docker/FrontEnds/app:/usr/share/nginx/html
    restart: always

  mongodocker:
    container_name: "MongoDBProd"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/MongoDB/mongoApp/data:/data/db
