version: "3"

# Used for Path reverse Proxy
# services:
# nginx:
#   container_name: "NginxMain"
#   image: nginx:stable-alpine
#   ports:
#     - "80:80"
#   volumes:
#     - ../NginxAndDocker/default.conf:/etc/nginx/conf.d/default.conf:ro
#   depends_on:
#     - expressdocker
#   networks:
#     - WebserverNetwork

services:
  nginxproxy:
    container_name: "nginxproxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - expressdocker
    networks:
      - WebserverNetwork

  expressdocker:
    container_name: "NodeServerMain"
    image: sandrospengler/myexpressapp
    build:
      context: .
    environment:
      - PORT=5000
      - DB_CONNECTION=""
      - VIRTUAL_HOST=app.localhost
    depends_on:
      - mongodocker
    networks:
      - WebserverNetwork
      - MongoDBNetwork

  mongodocker:
    container_name: "MongoDBMain"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=""
      - MONGO_INITDB_ROOT_PASSWORD=""
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - WebserverNetwork
      - MongoDBNetwork

networks:
  WebserverNetwork:
  MongoDBNetwork:
