version: "3"

# Used for Path reverse Proxy
# services:
# nginx:
#   container_name: "NginxMain"
#   image: nginx:stable-alpine
#   ports:
#     - "80:80"
#   volumes:
#     - ../NginxAndDocker/default.conf:/etc/nginx/conf.d/default.conf:ro
#   depends_on:
#     - expressdocker
#   networks:
#     - WebserverNetwork

services:
  nginxproxy:
    container_name: "nginxproxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ### required for Let's Encrypt certificates
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhosts:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - expressdocker
    networks:
      - WebserverNetwork

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=sandro.spengler@web.de
      - NGINX_PROXY_CONTAINER=proxy
    volumes_from:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
    networks:
      - WebserverNetwork
    restart: always


  expressdocker:
    container_name: "NodeServerMain"
    image: sandrospengler/myexpressapp
    build:
      context: .
    environment:
      - PORT=5000
      - DB_CONNECTION=""
      - VIRTUAL_HOST=docker.localhost
      - LETSENCRYPT_HOST=docker.localhost
    depends_on:
      - mongodocker
    networks:
      - WebserverNetwork
      - MongoDBNetwork

  mongodocker:
    container_name: "MongoDBMain"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=""
      - MONGO_INITDB_ROOT_PASSWORD=""
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - WebserverNetwork
      - MongoDBNetwork

networks:
  WebserverNetwork:
  MongoDBNetwork:

volumes:
  #### NGINX reverse proxy container volumes
  nginx_certs:
  nginx_vhosts:
  nginx_html: