### For Deployment in production environments - gets committed into the repo
version: "3"

services:
  expressdocker:
    container_name: "NodeServerProd"
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}
      - VIRTUAL_HOST=docker.sandrospengler.com
      - LETSENCRYPT_HOST=docker.sandrospengler.com
    command: npm run prod

  webdefault:
    image: nginx
    environment:
    ### ToDo: Change to your public DNS name
      - VIRTUAL_HOST="axfert.com"
      - LETSENCRYPT_HOST="axfert.com"
    restart: always

  webexpressapp:
    image: nginx
    environment:
    ### ToDo: Change to your public DNS name
      - VIRTUAL_HOST=""
      - LETSENCRYPT_HOST=""
    depends_on:
      - nginxproxy
    restart: always

  mongodocker:
    container_name: "MongoDBProd"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/mongo/data:/data/db
