version: "3"

services:
  # nginx:
  #   container_name: "NginxDev"
  #   image: nginx:stable-alpine
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ../NginxAndDocker/default.conf:/etc/nginx/conf.d/default.conf:ro

  expressdocker:
    container_name: "NodeServerDev"
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5000"
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=mongodb://sandro:12345asdF@mongodocker:27017/?authSource=admin
      - VIRTUAL_HOST=dev.localhost
    command: npm run dev

  mongodocker:
    container_name: "MongoDBDev"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sandro
      - MONGO_INITDB_ROOT_PASSWORD=12345asdF
    volumes:
      - ~/mongo/ExpressAndDocker/data:/data/db
