version: "3"

services:
  # nginx:
  #   container_name: "NginxProd"
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../NginxAndDocker/default.conf:/etc/nginx/conf.d/default.conf:ro

  expressdocker:
    container_name: "NodeServerProd"
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}
      - VIRTUAL_HOST=app.sandrospengler.com
    command: npm run prod

  mongodocker:
    container_name: "MongoDBProd"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/mongo/data:/data/db
